### ISSUE TITLE
Triangulation.hull clock-wise instead of counter-clockwise?

### ISSUE THREAD

**Issue by andreesteve** [mourner/delaunator-rs#12]
Thanks for the port!

The [docs](https://docs.rs/delaunator/0.2.0/delaunator/struct.Triangulation.html) indicate that the indices returned by Triangulation.hull are counter-clockwise.

```
hull: Vec<usize>
[−]
A vector of indices that reference points on the convex hull of the triangulation, counter-clockwise.
```

However I see them being returned clockwise. Which one is the right expectation?

Sample test:

```
use delaunator::*;

fn main() {
    let p = vec![
        Point { x: 0.0, y: 0.0 },
        Point { x: 1.0, y: 1.0 },
        Point { x: -1.0, y: 1.0 },
    ];
    triangulate(&p)
        .unwrap().hull.iter()
        .for_each(|s| println!("Hull {}: {:?}", *s, p[*s]));
}
```

for which I get:

```
Hull 0: [0, 0]
Hull 2: [-1, 1]
Hull 1: [1, 1]
```

**Comment by mourner** [comment]
It should be counter-clockwise (as a convention and to match delaunator in JS), so it might be a bug.

**Comment by andreesteve** [comment]
This was my mistake. I assumed the Y axis upright, in such orientation the triangle is oriented clockwise.
![image](https://user-images.githubusercontent.com/942449/122511972-fc61c800-cfbc-11eb-8a2a-b5659ec5ed9a.png)

However, the library expects Y to be pointing downwards, in which case the orientation is correct.

![image](https://user-images.githubusercontent.com/942449/122512031-18fe0000-cfbd-11eb-81a1-6f20cca2b560.png)
