### ISSUE TITLE
Filtering out new convex hull geometry?

### ISSUE THREAD

**Issue by emctague** [mourner/delaunator-rs#26]
Not quite an *issue* but there is no discussion section on this project; Is there any mechanism to filter out hull geometry that lies outside of the original concave polygon input? Simply filtering by halfedges[i] != EMPTY ends up eliminating some regular triangles too.

**Comment by andreesteve** [comment]
Not sure if I understand your question. What do you mean by geometry that is outside of the original input? Can you share an example input?

AFAIK, the output triangulation hull is always convex. Some points might be ignored in the triangulation if they are ~EPSILON distance to another point. Those might be inside or outside of the hull. If those are the points you are talking about, you could identify those by searching if they are part of any triangles.

**Comment by mourner** [comment]
No further response so closing.
